version: '3'

services:
    nginx:
        image: nginx
        volumes:
            - ./conf.d:/etc/nginx/conf.d
        depends_on:
            - backend
        ports:
            - 5042:5042
        networks:
            - main_network

    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - ${FRONTEND_PORT}:5000
        volumes:
            - ./client:/webapp/client
        env_file:
            - ./.env
        depends_on:
            - backend
        networks:
            - main_network

    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/webapp/server
        environment:
            DB_HOST: host.docker.internal
        env_file:
            - ./.env
        networks:
            - main_network

networks:
    main_network:
        driver: bridge