version: '3'

services:
    db:
        image: mysql:latest
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - '3307:3306'
        networks:
            - main_network

    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        tty: true
        environment:
            - DOCKER_ENV=true
            - FRONTEND_PORT=${FRONTEND_PORT:-5000}
        ports:
            - ${FRONTEND_PORT}:5000
        volumes:
            - ./client:/app/client
        depends_on:
            - backend
        networks:
            - main_network

    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - ${SERVER_PORT:-5041}:${SERVER_PORT:-5041}
            - ${API_PORT:-5042}:${API_PORT:-5042}
        volumes:
            - ./server:/app/server
        environment:
            NODE_ENV: production
            SERVER_PORT: ${SERVER_PORT:-5041}
            API_PORT: ${API_PORT:-5042}
            DB_HOST: db
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_DATABASE: ${DB_DATABASE}
        depends_on:
            - db
        networks:
            - main_network

networks:
    main_network:
        driver: bridge