version: '3'

services:
    
    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        tty: true
        environment:
            - DOCKER_ENV=true
            - FRONTEND_PORT=${FRONTEND_PORT:-5000}
        ports:
            - ${FRONTEND_PORT}:5000
        volumes:
            - ./client:/webapp/client
        depends_on:
            - backend
        networks:
            - main_network

    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - ${SERVER_PORT:-5041}:${SERVER_PORT:-5041}
            - ${API_PORT:-5042}:${API_PORT:-5042}
        volumes:
            - ./server:/webapp/server
        environment:
            NODE_ENV: production
            SERVER_PORT: ${SERVER_PORT:-5041}
            API_PORT: ${API_PORT:-5042}
            DB_PORT: ${DB_PORT:-3306}
            DB_HOST: host.docker.internal
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_DATABASE: ${DB_DATABASE}
        networks:
            - main_network

networks:
    main_network:
        driver: bridge