export const SET_PAGE_STATE = "SET_PAGE_STATE";
export const SET_IDS = "SET_IDS";
export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const SET_CONVERSATION = "SET_CONVERSATION";
export const SET_SECONDARY_PAGE_STATE = "SET_SECONDARY_PAGE_STATE";
export const SET_USERNAME = "SET_USERNAME";
