export const SET_FILTER_OPTION = 'SET_FILTER_OPTION';
export const TOGGLE_ADVANCED_SEARCH = 'TOGGLE_ADVANCED_SEARCH';
export const ADD_ADVANCED_AFFILIATED_FILTER = 'ADD_ADVANCED_AFFILIATED_FILTER';
export const REMOVE_ADVANCED_AFFILIATED_FILTER = 'REMOVE_ADVANCED_AFFILIATED_FILTER';
export const CLEAR_ADVANCED_AFFILIATED_FILTER = 'CLEAR_ADVANCED_AFFILIATED_FILTER';