export const SET_FILTER_OPTION = 'SET_FILTER_OPTION';
export const TOGGLE_ADVANCED_SEARCH = 'TOGGLE_ADVANCED_SEARCH';
export const ADD_ADVANCED_INDIVIDUAL_FILTER = 'ADD_ADVANCED_INDIVIDUAL_FILTER';
export const REMOVE_ADVANCED_INDIVIDUAL_FILTER = 'REMOVE_ADVANCED_INDIVIDUAL_FILTER';